---
- block:
  - name: create prometheus system group
    group:
      name: prometheus
      system: true
      state: present

  - name: create prometheus system user
    user:
      name: prometheus
      system: true
      shell: "/sbin/nologin"
      group: prometheus
      createhome: false
      home: "{{ prometheus_db_dir }}"

  when: not prometheus_docker_install

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: "{{ prometheus_id }}"
    group: "{{ prometheus_id }}"
    mode: 0755

- name: create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ prometheus_id }}"
    mode: 0750
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/conf.d"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"


- include: install_binary.yml
  when:
    - not prometheus_docker_install

- include: install_docker.yml
  when:
    - prometheus_docker_install

# - name: change pam falsefile limits for prometheus
#   pam_limits:
#     domain: "prometheus"
#     limit_item: falsefile
#     limit_type: "{{ item }}"
#     value: "1024"
#     use_max: true
#   with_items:
#       - soft
#       - hard
#   notify:
#     - restart prometheus
