---
- name: Setup DB volume for prometheus
  docker_volume:
    name: prometheus_db
    # driver_options:
    #   device: "{{ prometheus_db_dir }}"
    #   o: bind

- name: Setup network for prometheus
  docker_network:
    name: prometheus

- name: fetch prometheus docker image
  docker_image:
    name: "{{ prometheus_docker_image }}"
    tag: "v{{ prometheus_version }}"
