---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- include: preflight.yml
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- include: install.yml
  become: true
  tags:
    - prometheus_install

- include: configure.yml
  become: true
  tags:
    - prometheus_configure

- name: ensure prometheus service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  tags:
    - prometheus_run
  when:
    - not prometheus_docker_install

- name: ensure container is up
  docker_container:
    name: prometheus
    image: "{{ prometheus_docker_image }}:v{{ prometheus_version }}"
    volumes:
      - "prometheus_db:{{ __prometheus_db_container_dir }}:rw"
      - "{{ prometheus_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "{{ prometheus_config_dir }}/conf.d:{{ prometheus_config_dir }}/conf.d:ro"
      - "{{ prometheus_config_dir }}/rules:{{ prometheus_config_dir }}/rules:ro"
      - "{{ prometheus_config_dir }}/file_sd:{{ prometheus_config_dir }}/file_sd:ro"
    networks:
      - name: prometheus
    published_ports:
      - "{{ prometheus_web_listen_port }}:{{ prometheus_web_listen_port }}"
    labels: "{{ prometheus_docker_labels | default(omit) }}"
    command: "{{ lookup('template', './prometheus.cmdline.j2') | replace('\\\n','') }}"
  tags:
    - prometheus_run
  when:
    - prometheus_docker_install

- name: test if prometheus is running
  uri:
    url: "{{ prometheus_web_external_url | default('http://127.0.0.1:' ~ prometheus_web_listen_port) }}/metrics"
  tags:
    - prometheus_check
